services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/:/data

  mongo:
      image: mongo
      container_name: mongo
      restart: always
      ports:
        - '27017:27017'
      volumes:
        - ./mongo:/data/db
